// Single source of truth for supported locations.
// tidePort: null = inland (tides panel hidden); string = LINZ port key used by tides.js
// pwsStation: null = Open-Meteo only; string = TWC PWS station ID (CHC only)

export const LOCATIONS = [
  {
    id: "kaitaia",
    name: "Kaitaia",
    region: "New Zealand",
    lat: -35.1136, lon: 173.2655,
    timezone: "Pacific/Auckland",
    pwsStation: null,
    tidePort: "auckland",       // nearest LINZ port with constants
    tideLabel: "Kaitaia — Tides",
  },
  {
    id: "whangarei",
    name: "Whangārei",
    region: "New Zealand",
    lat: -35.7275, lon: 174.3236,
    timezone: "Pacific/Auckland",
    pwsStation: null,
    tidePort: "auckland",
    tideLabel: "Whangārei — Tides",
  },
  {
    id: "auckland",
    name: "Auckland",
    region: "New Zealand",
    lat: -36.8485, lon: 174.7633,
    timezone: "Pacific/Auckland",
    pwsStation: null,
    tidePort: "auckland",
    tideLabel: "Auckland — Tides",
  },
  {
    id: "tauranga",
    name: "Tauranga",
    region: "New Zealand",
    lat: -37.6878, lon: 176.1651,
    timezone: "Pacific/Auckland",
    pwsStation: null,
    tidePort: "tauranga",
    tideLabel: "Tauranga — Tides",
  },
  {
    id: "hamilton",
    name: "Hamilton",
    region: "New Zealand",
    lat: -37.7870, lon: 175.2793,
    timezone: "Pacific/Auckland",
    pwsStation: null,
    tidePort: null,
    tideLabel: null,
  },
  {
    id: "gisborne",
    name: "Gisborne",
    region: "New Zealand",
    lat: -38.6623, lon: 178.0176,
    timezone: "Pacific/Auckland",
    pwsStation: null,
    tidePort: "gisborne",
    tideLabel: "Gisborne — Tides",
  },
  {
    id: "rotorua",
    name: "Rotorua",
    region: "New Zealand",
    lat: -38.1368, lon: 176.2497,
    timezone: "Pacific/Auckland",
    pwsStation: null,
    tidePort: null,
    tideLabel: null,
  },
  {
    id: "taupo",
    name: "Taupō",
    region: "New Zealand",
    lat: -38.6857, lon: 176.0702,
    timezone: "Pacific/Auckland",
    pwsStation: null,
    tidePort: null,
    tideLabel: null,
  },
  {
    id: "new-plymouth",
    name: "New Plymouth",
    region: "New Zealand",
    lat: -39.0556, lon: 174.0752,
    timezone: "Pacific/Auckland",
    pwsStation: null,
    tidePort: "new-plymouth",
    tideLabel: "New Plymouth — Tides",
  },
  {
    id: "napier",
    name: "Napier",
    region: "New Zealand",
    lat: -39.4928, lon: 176.9120,
    timezone: "Pacific/Auckland",
    pwsStation: null,
    tidePort: "napier",
    tideLabel: "Napier — Tides",
  },
  {
    id: "palmerston-north",
    name: "Palmerston North",
    region: "New Zealand",
    lat: -40.3523, lon: 175.6082,
    timezone: "Pacific/Auckland",
    pwsStation: null,
    tidePort: null,
    tideLabel: null,
  },
  {
    id: "masterton",
    name: "Masterton",
    region: "New Zealand",
    lat: -40.9522, lon: 175.6583,
    timezone: "Pacific/Auckland",
    pwsStation: null,
    tidePort: null,
    tideLabel: null,
  },
  {
    id: "nelson",
    name: "Nelson",
    region: "New Zealand",
    lat: -41.2706, lon: 173.2840,
    timezone: "Pacific/Auckland",
    pwsStation: null,
    tidePort: "nelson",
    tideLabel: "Nelson — Tides",
  },
  {
    id: "wellington",
    name: "Wellington",
    region: "New Zealand",
    lat: -41.2865, lon: 174.7762,
    timezone: "Pacific/Auckland",
    pwsStation: null,
    tidePort: "wellington",
    tideLabel: "Wellington — Tides",
  },
  {
    id: "blenheim",
    name: "Blenheim",
    region: "New Zealand",
    lat: -41.5134, lon: 173.9612,
    timezone: "Pacific/Auckland",
    pwsStation: null,
    tidePort: "blenheim",
    tideLabel: "Blenheim — Tides",
  },
  {
    id: "westport",
    name: "Westport",
    region: "New Zealand",
    lat: -41.7500, lon: 171.5997,
    timezone: "Pacific/Auckland",
    pwsStation: null,
    tidePort: "westport",
    tideLabel: "Westport — Tides",
  },
  {
    id: "tekapo",
    name: "Tekapo",
    region: "New Zealand",
    lat: -44.0053, lon: 170.4775,
    timezone: "Pacific/Auckland",
    pwsStation: null,
    tidePort: null,
    tideLabel: null,
  },
  {
    id: "franz-josef",
    name: "Franz Josef",
    region: "New Zealand",
    lat: -43.3884, lon: 170.1815,
    timezone: "Pacific/Auckland",
    pwsStation: null,
    tidePort: null,
    tideLabel: null,
  },
  {
    id: "christchurch",
    name: "Christchurch",
    region: "New Zealand",
    lat: -43.5321, lon: 172.6362,
    timezone: "Pacific/Auckland",
    pwsStation: "ICHRIS810",
    tidePort: "lyttelton",
    tideLabel: "New Brighton Beach — Tides",
  },
  {
    id: "geraldine",
    name: "Geraldine",
    region: "New Zealand",
    lat: -44.0900, lon: 171.2356,
    timezone: "Pacific/Auckland",
    pwsStation: null,
    tidePort: null,
    tideLabel: null,
  },
  {
    id: "timaru",
    name: "Timaru",
    region: "New Zealand",
    lat: -44.3960, lon: 171.2553,
    timezone: "Pacific/Auckland",
    pwsStation: null,
    tidePort: "timaru",
    tideLabel: "Timaru — Tides",
  },
  {
    id: "queenstown",
    name: "Queenstown",
    region: "New Zealand",
    lat: -45.0312, lon: 168.6626,
    timezone: "Pacific/Auckland",
    pwsStation: null,
    tidePort: null,
    tideLabel: null,
  },
  {
    id: "dunedin",
    name: "Dunedin",
    region: "New Zealand",
    lat: -45.8788, lon: 170.5028,
    timezone: "Pacific/Auckland",
    pwsStation: null,
    tidePort: "dunedin",
    tideLabel: "Dunedin — Tides",
  },
  {
    id: "invercargill",
    name: "Invercargill",
    region: "New Zealand",
    lat: -46.4132, lon: 168.3538,
    timezone: "Pacific/Auckland",
    pwsStation: null,
    tidePort: "invercargill",
    tideLabel: "Invercargill — Tides",
  },
];

export function getLocation(id) {
  return LOCATIONS.find(l => l.id === id) ?? LOCATIONS.find(l => l.id === "christchurch");
}
